abstract class CoreClerkDetailsStates{}

class CoreClerkDetailsInitialState extends CoreClerkDetailsStates{}

class CoreClerkDetailsLoadingCreateChatState extends CoreClerkDetailsStates{}

class CoreClerkDetailsCreateChatSuccessState extends CoreClerkDetailsStates{}

class CoreClerkDetailsNavigateSuccessState extends CoreClerkDetailsStates{}
