abstract class ITGroupConversationStates{}

class ITGroupConversationInitialState extends ITGroupConversationStates{}

class ITGroupConversationChangeUserTypeState extends ITGroupConversationStates{}

class ITGroupConversationUploadingImagesState extends ITGroupConversationStates{}

class ITGroupConversationUploadImagesState extends ITGroupConversationStates{}

class ITGroupConversationSendMessageState extends ITGroupConversationStates{}

class ITGroupConversationPermissionDeniedState extends ITGroupConversationStates{}

class ITGroupConversationSelectImagesState extends ITGroupConversationStates{}

class ITGroupConversationIncreaseTimerSuccessState extends ITGroupConversationStates{}

class ITGroupConversationCreateDirectoryState extends ITGroupConversationStates{}

class ITGroupConversationAmpTimerSuccessState extends ITGroupConversationStates{}

class ITGroupConversationStartRecordSuccessState extends ITGroupConversationStates{}

class ITGroupConversationStopRecordSuccessState extends ITGroupConversationStates{}

class ITGroupConversationChangeRecordingState extends ITGroupConversationStates{}

class ITGroupConversationPlayStreamState extends ITGroupConversationStates{}

class ITGroupConversationListenStreamState extends ITGroupConversationStates{}

class ITGroupConversationCancelRecordSuccessState extends ITGroupConversationStates{}

class ITGroupConversationChangePlayerStateSuccessState extends ITGroupConversationStates{}

class ITGroupConversationChangeRecordPositionState extends ITGroupConversationStates{}

class ITGroupConversationToggleRecordSuccessState extends ITGroupConversationStates{}

class ITGroupConversationInitializeRecordSuccessState extends ITGroupConversationStates{}

class ITGroupConversationPlayRecordSuccessState extends ITGroupConversationStates{}

class ITGroupConversationEndRecordSuccessState extends ITGroupConversationStates{}

class ITGroupConversationSelectFilesState extends ITGroupConversationStates{}

class ITGroupConversationLoadingMessageState extends ITGroupConversationStates{}

class ITGroupConversationGetMessageSuccessState extends ITGroupConversationStates{}

class ITGroupConversationDownloadFileSuccessState extends ITGroupConversationStates{}

class ITGroupConversationLoadingDownloadFileState extends ITGroupConversationStates{

  final String fileName;

  ITGroupConversationLoadingDownloadFileState(this.fileName);
}

class ITGroupConversationSendMessageErrorState extends ITGroupConversationStates{

  final String error;

  ITGroupConversationSendMessageErrorState(this.error);

}
class ITGroupConversationGetMessageErrorState extends ITGroupConversationStates{

  final String error;

  ITGroupConversationGetMessageErrorState(this.error);

}
class ITGroupConversationDownloadFileErrorState extends ITGroupConversationStates{

  final String error;

  ITGroupConversationDownloadFileErrorState(this.error);

}
